name: Build Aseprite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Clone Skia
        run: |
          git clone https://github.com/aseprite/skia.git

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia ..

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-portable
          path: |
            build/bin/**/aseprite.exe
            build/bin/**/data/
